#!/usr/bin/env python

from lucy.models.job import Job

import datetime as dt
import schedule
import time


def job():
    length = dt.timedelta(hours=2)
    jobs = Job.dead_jobs(length)
    for job in jobs:
        job['builder'] = None
        job['assigned_at'] = None
        job.save()
        print("Pushing %s back into the pool" % (job['_id']))


schedule.every(5).minutes.do(job)


while True:
    schedule.run_pending()
    time.sleep(1)
